### ISSUE TITLE
Fix speed when multiple confetti drops triggered

### ISSUE THREAD

**Issue by alexandermendes** [alexandermendes/vue-confetti#1]
It currently speeds up every time!

**Comment by kfbow** [comment]
+1

**Comment by alexandermendes** [comment]
That was my first thought too. I think it's actually to do with the animation loop never being cancelled, so we end up with multiple loops running each updating those variables. Adding a fix now.

**Comment by alexandermendes** [comment]
Should be ok in v0.3.2
