### ISSUE TITLE
Use more than one image

### ISSUE THREAD

**Issue by makerovski** [alexandermendes/vue-confetti#144]
Hi guys, 

Thank you all for this awesome component!

I am working with images, is that possible to use more than just one? I have tried but somehow it do not work,

Here's my code:

![code](https://user-images.githubusercontent.com/86009432/163935884-d81d94a4-1c72-41a1-88a0-898bf4674523.png)

It only shows the first pattern, is that possible to get the others working too ?

Thank you very much!!

**Comment by bram2202** [comment]
Create a image particle per image,
This worked for me with multiple files

```
      particles: [
        {
          type: "image",
          url: flakePattern1,
        },
        {
          type: "image",
          url: flakePattern2,
        },
        <more here>
      ],
```

**Comment by makerovski** [comment]
> Create a image particle per image, This worked for me with multiple files
> 
> ```
>       particles: [
>         {
>           type: "image",
>           url: flakePattern1,
>         },
>         {
>           type: "image",
>           url: flakePattern2,
>         },
>         <more here>
>       ],
> ```

Thank you very much, it worked perfectly!
