### ISSUE TITLE
Allow to append canvas to custom element

### ISSUE THREAD

**Issue by georgehrke** [alexandermendes/vue-confetti#21]
Right now, the canvas always covers the entire screen and is always appended to the body.
https://github.com/alexandermendes/vue-confetti/blob/5d562de18cde228e40106857a2ab0e5d8daf2bcc/src/canvas.js#L27

It would be very helpful if you could define a custom parent element, width and height. If no width and height are given, it should take these properties from the parent element.

**Comment by alexandermendes** [comment]
I like it, v1.3.0 will contain a `canvasId` property to pass in the ID of a custom canvas. Let me know how that works out.
