### ISSUE TITLE
Custom shape?

### ISSUE THREAD

**Issue by katieben** [alexandermendes/vue-confetti#22]
I'd love to be able to use a custom shape, provide the svg. Thanks for this, this is awesome!!

**Comment by alexandermendes** [comment]
Interesting idea, trying it out now 😄

**Comment by alexandermendes** [comment]
Seems like it might be pretty demanding on the browser and slows down sometimes, might need some tweaks, but is this the kind of thing you were thinking of (see "Custom Image" under shape)?

https://alexandermendes.github.io/vue-confetti/

**Comment by katieben** [comment]
Yes! Thank you!! Good to know it's demanding on the browser, that makes sense that it might be. I"ll play with this. Thank you!

**Comment by alexandermendes** [comment]
You're welcome 🙂
