### ISSUE TITLE
1.3.0 bug of canvasId not defined

### ISSUE THREAD

**Issue by shikinen** [alexandermendes/vue-confetti#26]
Hi there! It seems that with v 1.3.0 you need to specify canvasId element – the default of appending confetti canvas to body results in an error. :(

Btw, I love the package and it would be awesome to be able to mix different shapes at once, even some custom ones! :)

**Comment by alexandermendes** [comment]
Uh oh, will check it out, thanks!

And yeah, nice idea, crossed my mind too, will get to it sometime :smile:

**Comment by alexandermendes** [comment]
So this is strange as the demo is also just appending the default canvas to the body element. Have also checked when no properties are being passed in at all. Did you notice any JS errors that might help?

**Comment by alexandermendes** [comment]
Also, v.2.0.0 contains the ability to pass in whatever set of particles you like 😄

**Comment by isidoravs** [comment]
Hi! I think I may be having the same issue. This is the console error I'm getting:
`[Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'canvasId' of undefined"`

Thank you.

**Comment by alexandermendes** [comment]
Going to tackle this in https://github.com/alexandermendes/vue-confetti/issues/28 as they seem related.
