### ISSUE TITLE
getContext not a function

### ISSUE THREAD

**Issue by larsjanssen6** [alexandermendes/vue-confetti#28]
Cool package!

When I install it out of the box I get this error:

`
Error in created hook: "TypeError: this.canvas.getContext is not a function"
`
What could I be doing wrong here >?

Thx!

**Comment by larsjanssen6** [comment]
Passed in a default getContext now it's working but this looks like a bug :)

**Comment by alexandermendes** [comment]
Thanks, I'll try to check this out soon

**Comment by noreason** [comment]
Same issue. Care to share the solution? @larsjanssen6

**Comment by alexandermendes** [comment]
Have added some additional checks for the canvasId in v2.0.1. Could someone check and if it doesn't work let me know the steps to reproduce?

**Comment by larsjanssen6** [comment]
@alexandermendes yes it seems to be fixed now in 2.0.1. Thankyou 👍
