### ISSUE TITLE
this.$confetti.start() throws error, when there are no arguments

### ISSUE THREAD

**Issue by muratkemaldar** [alexandermendes/vue-confetti#3]
Hey, thanks for the confetti library.

Just wanted to say that if you use `this.$confetti.start()`, it will throw an error and say `opts is undefined`.

Works if you pass an empty object, like this:
`this.$confetti.start({})`

**Comment by alexandermendes** [comment]
Thanks for that, it should be fixed in v0.3.3.

**Comment by muratkemaldar** [comment]
You are welcome 👍
