### ISSUE TITLE
globalCompositeOperation question

### ISSUE THREAD

**Issue by isidoravs** [alexandermendes/vue-confetti#30]
Hello,

Is there a way to change only the `globalCompositeOperation` of the default canvas? I'm trying to set it to `'destination-over'` with no success.

Thank you!

**Comment by alexandermendes** [comment]
Hi, there's nothing exactly built in, but the canvas is a property of the confetti object. So, after running `confetti.start()` you could try `confetti.canvas.ctx.globalCompositeOperation = 'destination-over'`

**Comment by isidoravs** [comment]
Thank you! I also solved it changing the `z-index` with the `confetti-canvas` id.

**Comment by cdecinkoKnight** [comment]
> Thank you! I also solved it changing the `z-index` with the `confetti-canvas` id.

What method did you use to change the z-index?

**Comment by isidoravs** [comment]
> > Thank you! I also solved it changing the `z-index` with the `confetti-canvas` id.
> 
> What method did you use to change the z-index?

I just styled it like this:
```CSS
#confetti-canvas {
  z-index: 1000;
}
```
