### ISSUE TITLE
WIP: Compatibility with server side rendering

### ISSUE THREAD

**Issue by emdahlstrom** [alexandermendes/vue-confetti#33]
_This bug report is a WIP. There are still things I haven't tried and this bug report needs more information. It's hard to experiment in my codebase because vue-confetti is used in so many places so I need to set up a clean Nuxt project and experiment there. It's not possible to do it on CodeSandbox because the error makes it freeze._ 

I use vue-confetti in a Nuxt application with server side rendering. 

When I try to upgrade vue-confetti from 0.3.3 to 0.5.1 I get the following error:
```
referenceError: window is undefined
```

When I try to upgrade vue-confetti to 2.0.1 the web browser just freezes when it loads the page so I don't get an error, but if I try to generate a static site I get the same error:

```
ReferenceError: window is not defined
    at Object.<anonymous> (/node_modules/vue-confetti/dist/vue-confetti.js:1:274)
```

There is a standard solution in Nuxt for handling plugins that arent ssr-safe and that is to only require them when a browser is detected: https://nuxtjs.org/faq/window-document-undefined/

```
if (process.client) {
  require('external_library')
}
```

-  I tried a solution based on this with 0.5.1 but I got the same error. I also moved "Vue.use(VueConfetti)" in there
-  I also tried to only use the confetti methods (like $confetti.start) when a browser is detected but that didn't work either

**Comment by alexandermendes** [comment]
Thanks for pointing this out. I guess it makes sense that it won't work when server-side rendered,   but it could do with something in the docs. So, what about if you have a plugins file to register file plugin, like:

```js
// /your-repo/plugins/vue-confetti.js

import Vue from 'vue'
import VueConfetti from 'vue-confetti'

Vue.use(VueConfetti)
```

Then in your nuxt config:

```js
export default {
  plugins: [
    { src: '~/plugins/vue-confetti.js', mode: 'client' },
  ],
}
```

Basically this https://nuxtjs.org/guide/plugins/#client-side-only

Then ensure you only call the functions like `confetti.start()` on the client, so in a response to a click action somewhere, or whatever it is. Or, wrapping with `process.client`, as you say.

**Comment by emdahlstrom** [comment]
Thanks for looking into this! Really appreciate it!

I did what you suggested and that got me past window undefined. 

The next hurdle is 'Cannot read property 'canvasId' of undefined', any insight there?

Here is a codesandbox:
https://codesandbox.io/embed/confettilab-016g9

**Comment by alexandermendes** [comment]
For now `confetti.start` expects some options object to be passed, so if you call it with `this.$confetti.start({})` it should work. 

This is definitely something to fix though, will try to deal with it soon!

**Comment by emdahlstrom** [comment]
Ah, excellent! Thanks! That works. Really appreciate all the help! Close if you want to.

**Comment by alexandermendes** [comment]
Just pushed up a small fix for the confetti.start thing so closing now!
