### ISSUE TITLE
Confetti doesn't work in a Cordova app

### ISSUE THREAD

**Issue by katieben** [alexandermendes/vue-confetti#34]
Hi there - this plugin doesn't work in a Cordova app, (tested iPhone & Android), though the same exact code works directly on the web, both iPhone & Android. Any ideas on what might be the issue?

**Comment by katieben** [comment]
... or how I might go about figuring out what the issue is? Maybe this is a lead: on a regular browser, if I take out all my options and just have this.$confetti.start(), I get this error:

` Cannot read property 'canvasId' of undefined`

If I add the option, canvasId: 'background-container' (I have a div with id background-container), I get the error: 

` Element with ID "confetti-canvas" is not a valid HTMLCanvasElement`

So then I added a div with ID confetti-canvas, and still got the same error, even if I also updated my canvasId option to 'confetti-canvas'.

This is all on on 2.0.1. Thanks for any ideas. :)

**Comment by msolomonTMG** [comment]
@katieben Idk about the Cordova app but to workaround the issue:
`Cannot read property 'canvasId' of undefined`
This did the trick for me: https://github.com/alexandermendes/vue-confetti/issues/32#issuecomment-524102651

**Comment by katieben** [comment]
Thanks, @msolomonTMG. I don't think this is it for me - adding to this thread, I've since realized that the confetti *does* work on the fifth call. I have this.$confetti.start({}) and this.$confetti.stop({}) in four places across my app (powered by Vue router). So it's super weird, but I'm wondering if it has something to do with that.

**Comment by katieben** [comment]
Ah, I figured it out! Not fully, but enough to think this is a problem with my code, not confetti. I have confetti stopping with every route change. When I take that out, confetti works as expected on the first call.

**Comment by katieben** [comment]
Update: I figured it out completely. I just needed to check that confetti was actually running before calling stop. I'm not sure why this prevented confetti from running those first 4 times, but anyway, solution! It would be helpful to have a this.$confetti.isRunning variable. For now I just used local storage and set/got it myself.

**Comment by alexandermendes** [comment]
Just pushed up a small fix for the confetti.start issue, so v2.0.5 should work without `this.$confetti.start({})`. 

Not sure about the subsequent issue. All stop does is set some variables that end up stopping future iterations of the animation loop. 

https://github.com/alexandermendes/vue-confetti/blob/d3423763b2adc23da911c23964fc7763143229ba/src/confetti.js#L92-L95

If there is no loop running in the first place it shouldn't do anything. Maybe some kind of race condition going on and it's being stopped from elsewhere the millisecond after it starts 🤔
