### ISSUE TITLE
Does not work inside a component rendered with v-if or v-show

### ISSUE THREAD

**Issue by thomaskvael** [alexandermendes/vue-confetti#35]
Hi

This plugin does not work when you put a canvas inside a component that is shown/hidden.

Steps to reproduce.

`<Confetti v-if="isVisible"></Confetti>`

If you put a canvas inside the Confetti component. And then tries to toggle isVisible between false and true it will only show the confetti the first time. Next time the canvas is visible it will not throw confetti.

**Comment by Eschricht** [comment]
I had a similar problem but was able to solve this by removing the confetti just after stopping it.
An example with the `beforeDestroy`-lifecycle hook:
```
mounted() {
  this.$nextTick(() => {
    this.$confetti.start();
  });
},
beforeDestroy() {
  this.$confetti.stop();
  this.$confetti.remove();
},
```

**Comment by alexandermendes** [comment]
Possible this is sorted now that `remove()` is called by `start()` (to reset defaults).

**Comment by alexandermendes** [comment]
Well as above, might be fixed ☝️ Feel free to reopen if not
