### ISSUE TITLE
Starting and stopping "piles up" the confetti

### ISSUE THREAD

**Issue by m-vdv** [alexandermendes/vue-confetti#36]
Hi guys

I find this rather odd behaviour...
When you start confetti and let it run for a few seconds then stop the confetti and wait, let's say 30 seconds. You get a huge amount of confetti when you start it again, as if during those 30 seconds wait time the confetti "piled up" at the top of the browser window.

See screenshot (confetti started with a huge amount of confettis):
https://imgur.com/a/YWVpSty

You can also test this behaviour on the demo page: 
https://alexandermendes.github.io/vue-confetti/

Expected behaviour:
$confetti.stop() should stop all confetti, until $confetti.start() is run and brand new confetti is created.

Unless I'm missing something here?

**Comment by weihao** [comment]
Same issue here.

**Comment by alexandermendes** [comment]
I'll try to get to this at some point, in the meantime PRs always welcome if anyone else wants to have a go 😄

**Comment by backmeupplz** [comment]
Yeah, same here on Firefox

**Comment by alexandermendes** [comment]
Should be (finally) fixed in [`v2.1.1`](https://github.com/alexandermendes/vue-confetti/releases/tag/v2.1.1).
