### ISSUE TITLE
Memory consumption issue

### ISSUE THREAD

**Issue by nehalshah50** [alexandermendes/vue-confetti#58]
I used this plugin and I noticed that if you use a lot of confetti over and over. The website stops responding due to heavy memory consumption. It looks like it has some sort of memory leaks. Or it doesn't clean up the components in the memory when confetti is stopped

**Comment by alexandermendes** [comment]
Ah, thanks, yeah that sounds quite likely, I will look into it 👀

**Comment by nehalshah50** [comment]
Thx. I have this website project where I use it after every correct answer for a question. And I have about 50 questions. So this issue occurs after 20 to 25th attempt. If there is a way to clean memory after each drop then that would be great

**Comment by Julzso23** [comment]
I just ran into this issue and I'm guessing it's because every time you start the confetti it creates another canvas element and doesn't remove it when you stop it:
![image](https://user-images.githubusercontent.com/3117728/113747324-2d8d6480-96ff-11eb-8041-0be09fc8260c.png)

**Comment by phoheisel** [comment]
would love to see that fixed as i only wanna use it for success notifications :)
