### ISSUE TITLE
Why vue dependent?

### ISSUE THREAD

**Issue by ramesaliyev** [alexandermendes/vue-confetti#7]
Hi, thanks for the cool project. But why this is vue dependent? It would be better if you export `Confetti` to make it available for standalone usage.

**Comment by Kocal** [comment]
The main import is a Vue wrapper, but you can still import `Confetti` class manually:

```js
import Confetti from 'vue-confetti/src/confetti';

const confetti = new Confetti(options);
```

Also this package is no Vue dependent, there is no Vue dependency in [package.json(https://github.com/alexandermendes/vue-confetti/blob/master/package.json).

**Comment by Kocal** [comment]
That's true, it would be nice to be able to do something like that: 
```js
import VueConfetti, { Confetti } from 'vue-confetti'
```

**Comment by alexandermendes** [comment]
Yeah, I was working on a Vue project at the time, which is largely why it became a Vue plugin. But you're right, it's not really Vue dependant and I was thinking about changing it at some point. Might have a look over the weekend!

**Comment by alexandermendes** [comment]
As people could already be relying on this as "vue-confetti" maybe we just pull out the Confetti part to a seperate repo and keep this as a Vue wrapper of some kind.

**Comment by alexandermendes** [comment]
Actually just went with exporting Confetti from index.js. Peer dependency to Vue also added. Hopefully that will do!
