### ISSUE TITLE
Any chance of a quantity prop?

### ISSUE THREAD

**Issue by jamiecarter7** [alexandermendes/vue-confetti#8]
Great little plugin!

I just wish I could tone down the number of particles being generated.

Would be great to have:

```javascript
$confetti.start({
  shape: 'heart',
  colors: ['red', 'pink', '#ba0000'],
  count: 30
})```

**Comment by alexandermendes** [comment]
Good idea, actually looking back at this those options could generally be a little more flexible, will try to take a look soon.

**Comment by alexandermendes** [comment]
Take a look at v1.5.0, it adds a `particlesPerFrame` option, for example:

```
$confetti.start({
  particlesPerFrame: 0.25
});
```

**Comment by katieben** [comment]
Works beautifully! Thank you!
