### ISSUE TITLE
Change the size of particles?

### ISSUE THREAD

**Issue by miguejarias** [alexandermendes/vue-confetti#9]
It would be cool to change the size of the particles. Make them smaller or something

**Comment by alexandermendes** [comment]
Nice idea, will check it out

**Comment by alexandermendes** [comment]
This is available in the just released v0.5.0, see the `size` prop, hope that works for you!

[Here's a demo](https://alexandermendes.github.io/vue-confetti/)

**Comment by miguejarias** [comment]
Thanks its perfect!
